{% set name = "cloudsplaining" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cloudsplaining-{{ version }}.tar.gz
  sha256: 2d8a1d1a3261368a39359bb23aa7d6ac9add274728ff24877b710cdfa96d96af

build:
  entry_points:
    - cloudsplaining=cloudsplaining.bin.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - boto3
    - botocore
    - cached-property
    - click
    - click-option-group
    - jinja2
    - markdown
    - policy_sentry <0.14,>=0.13.0
    - pyyaml
    - schema

test:
  imports:
    - cloudsplaining
  commands:
    - pip check
    - cloudsplaining --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/salesforce/cloudsplaining
  summary: AWS IAM Security Assessment tool that identifies violations of least privilege and generates a risk-prioritized HTML report.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - borchero
    - nick-harmening
