{% set name = "cloudsplaining" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cloudsplaining-{{ version }}.tar.gz
  sha256: d3e7a327710b604a26db30d9c7134b15b73a4eaf9e86ed864f554013aed718d8

build:
  entry_points:
    - cloudsplaining=cloudsplaining.bin.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - boto3
    - botocore
    - cached-property
    - click
    - click-option-group
    - jinja2
    - markdown
    - policy_sentry >=0.14.0,<0.15
    - pyyaml
    - schema

test:
  imports:
    - cloudsplaining
  commands:
    - pip check
    - cloudsplaining --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/salesforce/cloudsplaining
  summary: AWS IAM Security Assessment tool that identifies violations of least privilege and generates a risk-prioritized HTML report.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - borchero
    - nick-harmening
